### ISSUE TITLE
Too much space after properties

### ISSUE THREAD

**Issue by frankenjoe** [audeering/sphinx-audeering-theme#57]
It seems there is more space after properties than methods or attributes, e.g.:

![image](https://user-images.githubusercontent.com/10383417/167912745-39f1ecba-66c3-4748-9bf3-ba0e99a4a4a0.png)

https://audeering.github.io/audformat/api.html#table

**Comment by hagenw** [comment]
Good observation. I also have recognized that properties seem to be handled differently as it can happen that they are listed beside each other if they are small:

![image](https://user-images.githubusercontent.com/173624/168004246-01db6b3d-3262-4efe-be10-74561712df82.png)

The related CSS entry seems to be this one:

```css
.rst-content dl:not(.docutils) .property {
  display: inline-block;
  padding-right: 8px;
}
```

If we remove this we get

![image](https://user-images.githubusercontent.com/173624/168004508-2a2c401c-36a0-4541-a714-7ab9b5800af7.png)

which also has the right bottom margin.
